// Developer Express Code Central Example:
// How to implement the ItemsSource property for the LayoutControl control
// 
// This example demonstrates how to implement the ItemsSource property for the
// LayoutControl control. The ItemsSource property is implemented as an attached
// property and allows you to bind a collection and its items are used for
// generating layout items.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E5081

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayoutControlItemsSource.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
